# Generated by Django 5.0.2 on 2024-03-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('timezone', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('iata_code', models.CharField(max_length=3)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='flights.city')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(verbose_name='Departure Date')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival Date')),
                ('flight_duration', models.IntegerField(verbose_name='Flight Duration')),
                ('flight_distance', models.IntegerField(verbose_name='Flight Distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='flights.city')),
                ('destination_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='flights.city')),
            ],
        ),
    ]
