# Generated by Django 5.0.2 on 2024-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
