# Generated by Django 5.0.2 on 2024-03-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_city_code_alter_city_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
    ]
