# Generated by Django 5.0.2 on 2024-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport',
            field=models.CharField(max_length=50),
        ),
    ]
