# Generated by Django 5.0.2 on 2024-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_flight_departure_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='offer_link',
            field=models.TextField(blank=True, default='Link here', null=True),
        ),
    ]
