# Generated by Django 5.0.2 on 2024-03-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_city_code_alter_city_population_and_more'),
        ('monitor', '0002_alter_monitoredflight_best_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredflight',
            name='best_flight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_flight', to='flights.flight'),
        ),
    ]
