# Generated by Django 5.0.2 on 2024-03-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_monitoredflight_best_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredflight',
            name='alert_email',
            field=models.EmailField(default='test@mail.com', max_length=50),
            preserve_default=False,
        ),
    ]
