# Generated by Django 5.0.2 on 2024-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitoredflight_alert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredflight',
            name='IATA_from',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoredflight',
            name='IATA_to',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
    ]
