# Generated by Django 5.0.2 on 2024-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_monitoredflight_iata_from_monitoredflight_iata_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredflight',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='monitoredflight',
            name='date_to',
            field=models.DateTimeField(),
        ),
    ]
