# Generated by Django 5.0.2 on 2024-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_monitoredflight_date_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoredflight',
            old_name='IATA_to',
            new_name='IATA_arrival',
        ),
        migrations.RenameField(
            model_name='monitoredflight',
            old_name='IATA_from',
            new_name='IATA_departure',
        ),
    ]
